# Generated by Django 3.1.7 on 2021-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentvehicle',
            name='book_day',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='paid_status',
            field=models.CharField(choices=[('UnPaid', 'UnPaid'), ('Paid', 'Paid')], default='UnPaid', max_length=15),
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
