# Generated by Django 3.1.7 on 2021-03-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20210307_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price_per_day',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
