# Generated by Django 3.1.7 on 2021-03-08 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_vehicle_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentvehicle',
            name='book_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='book_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
